# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-01-29 10:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import shortuuidfield.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0001_initial'),
        ('connections', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', shortuuidfield.fields.ShortUUIDField(blank=True, editable=False, max_length=22)),
                ('slug', models.CharField(max_length=80, unique=True)),
                ('name', models.CharField(max_length=80)),
                ('make', models.CharField(blank=True, max_length=80)),
                ('model', models.CharField(blank=True, max_length=80)),
                ('type', models.CharField(blank=True, max_length=80)),
                ('purchase_date', models.DateField(blank=True, null=True)),
                ('purchase_amount', models.CharField(blank=True, max_length=20)),
                ('base_rate', models.CharField(blank=True, max_length=5)),
                ('service_lag', models.CharField(max_length=5)),
                ('additional_info', models.TextField(blank=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='EquipmentBooking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', shortuuidfield.fields.ShortUUIDField(blank=True, editable=False, max_length=22)),
                ('slug', models.CharField(max_length=80, unique=True)),
                ('name', models.CharField(blank=True, max_length=80)),
                ('project_name', models.CharField(blank=True, max_length=80)),
                ('company_name', models.CharField(blank=True, max_length=80)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('additional_info', models.TextField(blank=True)),
                ('bookings_days', models.SmallIntegerField(blank=True, null=True)),
                ('booking_cost', models.CharField(blank=True, max_length=6, null=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('order', models.IntegerField(default=0)),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='connections.Company')),
                ('equipment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='equipment.Equipment')),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='projects.Project')),
            ],
        ),
    ]
