# Generated by Django 2.0.6 on 2018-06-13 01:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('equipment', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='equipment',
            options={'verbose_name_plural': 'Equipment'},
        ),
        migrations.AlterModelOptions(
            name='equipmentbooking',
            options={'verbose_name': 'Equipment booking'},
        ),
        migrations.RenameField(
            model_name='equipment',
            old_name='type',
            new_name='equipment_type',
        ),
        migrations.RemoveField(
            model_name='equipment',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='equipment',
            name='uuid',
        ),
        migrations.RemoveField(
            model_name='equipmentbooking',
            name='company_name',
        ),
        migrations.RemoveField(
            model_name='equipmentbooking',
            name='name',
        ),
        migrations.RemoveField(
            model_name='equipmentbooking',
            name='order',
        ),
        migrations.RemoveField(
            model_name='equipmentbooking',
            name='project_name',
        ),
        migrations.RemoveField(
            model_name='equipmentbooking',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='equipmentbooking',
            name='uuid',
        ),
        migrations.AddField(
            model_name='equipment',
            name='created_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='equipmentbooking',
            name='created_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='equipmentbooking',
            name='company',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='connections.Company'),
        ),
        migrations.AlterField(
            model_name='equipmentbooking',
            name='equipment',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='equipment.Equipment'),
        ),
        migrations.AlterField(
            model_name='equipmentbooking',
            name='project',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='projects.Project'),
        ),
    ]
