# Generated by Django 2.0.4 on 2018-07-03 12:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('equipment', '0002_auto_20180613_1142'),
    ]

    operations = [
        migrations.CreateModel(
            name='Equipment_AdditionalInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_type', models.CharField(blank=True, max_length=20)),
                ('toll_tag_no', models.CharField(blank=True, max_length=20)),
                ('fuel_card_no', models.CharField(blank=True, max_length=40)),
                ('fuel_card_pin', models.CharField(blank=True, max_length=8)),
                ('odometer_prompt', models.BooleanField()),
                ('product_restriction', models.CharField(blank=True, max_length=20)),
                ('created_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='equipmentbooking',
            name='company',
        ),
        migrations.RemoveField(
            model_name='equipmentbooking',
            name='created_user',
        ),
        migrations.RemoveField(
            model_name='equipmentbooking',
            name='equipment',
        ),
        migrations.RemoveField(
            model_name='equipmentbooking',
            name='project',
        ),
        migrations.RemoveField(
            model_name='equipment',
            name='base_rate',
        ),
        migrations.RemoveField(
            model_name='equipment',
            name='equipment_type',
        ),
        migrations.RemoveField(
            model_name='equipment',
            name='name',
        ),
        migrations.RemoveField(
            model_name='equipment',
            name='service_lag',
        ),
        migrations.AddField(
            model_name='equipment',
            name='Maintenance',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='equipment',
            name='engine_no',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name='equipment',
            name='equipment_id',
            field=models.CharField(default='def', max_length=20, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='equipment',
            name='fuel',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='equipment',
            name='height_restrictor',
            field=models.BooleanField(default='0'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='equipment',
            name='registration',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name='equipment',
            name='rubber_tracks',
            field=models.BooleanField(default='0'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='equipment',
            name='size',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name='equipment',
            name='vin',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name='equipment',
            name='year',
            field=models.CharField(blank=True, max_length=5),
        ),
        migrations.DeleteModel(
            name='EquipmentBooking',
        ),
        migrations.AddField(
            model_name='equipment_additionalinfo',
            name='equipment_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='equipment.Equipment'),
        ),
    ]
