# Generated by Django 2.0.4 on 2018-07-03 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0003_auto_20180703_2258'),
    ]

    operations = [
        migrations.RenameField(
            model_name='equipment',
            old_name='Maintenance',
            new_name='maintenance',
        ),
        migrations.AlterField(
            model_name='equipment',
            name='height_restrictor',
            field=models.BooleanField(default=0),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='rubber_tracks',
            field=models.NullBooleanField(),
        ),
    ]
