# Generated by Django 2.0.6 on 2018-08-12 09:48

from django.db import migrations, models
import shortuuidfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0005_auto_20180812_1938'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipment',
            name='slug',
            field=models.CharField(default='Test', max_length=80, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='equipment',
            name='uuid',
            field=shortuuidfield.fields.ShortUUIDField(blank=True, editable=False, max_length=22),
        ),
    ]
