# Generated by Django 2.0.6 on 2018-08-12 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0006_auto_20180812_1948'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='equipment',
            name='description',
        ),
        migrations.AddField(
            model_name='equipment',
            name='make',
            field=models.CharField(default='TEST', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='equipment',
            name='model',
            field=models.CharField(default='TEST', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='equipment',
            name='year',
            field=models.CharField(default='2018', max_length=12),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='equipment',
            name='engine_no',
            field=models.CharField(max_length=80),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='registration',
            field=models.CharField(max_length=80),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='vin',
            field=models.CharField(max_length=80),
        ),
    ]
