# Generated by Django 2.0.6 on 2018-08-12 10:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0007_auto_20180812_2042'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='equipment',
            name='engine_no',
        ),
        migrations.RemoveField(
            model_name='equipment',
            name='vin',
        ),
    ]
