# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-02-16 20:51
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import shortuuidfield.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0001_initial'),
        ('equipment', '0001_initial'),
        ('connections', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Timesheet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', shortuuidfield.fields.ShortUUIDField(blank=True, editable=False, max_length=22)),
                ('slug', models.CharField(max_length=80, unique=True)),
                ('docket_date', models.DateField(blank=True, null=True)),
                ('docket_shift', models.CharField(blank=True, choices=[('Day', 'Day'), ('Night', 'Night')], max_length=20)),
                ('equipment_name', models.CharField(blank=True, max_length=80)),
                ('equipment_num', models.CharField(blank=True, max_length=80)),
                ('equipment_hours', models.CharField(blank=True, max_length=80)),
                ('docket_number', models.CharField(blank=True, max_length=80)),
                ('company_name', models.CharField(blank=True, max_length=80)),
                ('project_name', models.CharField(blank=True, max_length=80)),
                ('start_time', models.TimeField(blank=True, null=True)),
                ('finish_time', models.TimeField(blank=True, null=True)),
                ('lunch', models.CharField(blank=True, choices=[('0', '0 min'), ('5', '5 mins'), ('10', '10 mins'), ('15', '15 mins'), ('20', '20 mins'), ('25', '25 mins'), ('30', '30 mins'), ('35', '35 mins'), ('40', '40 mins'), ('45', '45 mins'), ('50', '50 mins'), ('55', '55 mins'), ('60', '60 mins')], max_length=20)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='connections.Company')),
                ('equipment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='equipment.Equipment')),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='projects.Project')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
