# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-03-17 03:48
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timesheet', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='timesheet',
            name='user_name',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AlterField(
            model_name='timesheet',
            name='docket_date',
            field=models.DateField(blank=True, default=datetime.date(2018, 3, 17), null=True),
        ),
    ]
