# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-04-03 08:42
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timesheet', '0002_auto_20180317_1348'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='timesheet',
            name='user',
        ),
        migrations.RemoveField(
            model_name='timesheet',
            name='user_name',
        ),
        migrations.AlterField(
            model_name='timesheet',
            name='docket_date',
            field=models.DateField(blank=True, default=datetime.date(2018, 4, 3), null=True),
        ),
    ]
