# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-04-16 01:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('timesheet', '0003_auto_20180403_1842'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timesheet',
            name='docket_date',
            field=models.DateField(blank=True, default=django.utils.timezone.now, null=True),
        ),
    ]
