# Generated by Django 2.0.5 on 2018-05-23 00:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('daily_dockets', '0014_auto_20180523_1043'),
        ('timesheet', '0005_timesheet_created_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='timesheet',
            options={'ordering': ('created_user__id', '-docket__docket_num')},
        ),
        migrations.AddField(
            model_name='timesheet',
            name='docket',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='daily_dockets.Docket'),
        ),
        migrations.AlterField(
            model_name='timesheet',
            name='slug',
            field=models.SlugField(blank=True, null=True),
        ),
        migrations.RemoveField(
            model_name='timesheet',
            name='docket_number',
        ),
        migrations.AlterUniqueTogether(
            name='timesheet',
            unique_together={('created_user', 'docket')},
        ),
    ]
