# Generated by Django 2.0.5 on 2018-05-23 00:54

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('timesheet', '0006_auto_20180523_1043'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='timesheet',
            options={'ordering': ('created_user__id', '-timesheet_num')},
        ),
        migrations.AddField(
            model_name='timesheet',
            name='timesheet_num',
            field=models.PositiveSmallIntegerField(blank=True, default=1000, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='timesheet',
            unique_together={('created_user', 'timesheet_num')},
        ),
    ]
