# Generated by Django 2.0.5 on 2018-05-23 01:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('daily_dockets', '0014_auto_20180523_1043'),
        ('timesheet', '0007_auto_20180523_1054'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='timesheet',
            name='docket',
        ),
        migrations.AddField(
            model_name='timesheet',
            name='dockets',
            field=models.ManyToManyField(blank=True, to='daily_dockets.Docket'),
        ),
    ]
