# Generated by Django 2.0.5 on 2018-05-23 02:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('timesheet', '0008_auto_20180523_1103'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='timesheet',
            name='uuid',
        ),
    ]
