# Generated by Django 2.0.6 on 2018-08-07 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timesheet', '0010_auto_20180806_2125'),
    ]

    operations = [
        migrations.AddField(
            model_name='timesheet',
            name='submitted',
            field=models.BooleanField(default=False),
        ),
    ]
