# Generated by Django 2.0.6 on 2018-08-07 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timesheet', '0012_auto_20180807_2029'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timesheet',
            name='status',
            field=models.CharField(blank=True, choices=[('Open', 'Open'), ('Submitted', 'Submitted'), ('Approved', 'Approved')], default='Open', max_length=20),
        ),
    ]
