# Generated by Django 2.0.6 on 2018-08-10 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timesheet', '0014_auto_20180808_1520'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timesheet',
            name='docket_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
