# Generated by Django 2.0.6 on 2018-08-17 11:14

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('timesheet', '0016_timesheet_docket_date_end'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='timesheet',
            name='docket_date',
        ),
        migrations.RemoveField(
            model_name='timesheet',
            name='docket_date_end',
        ),
        migrations.AddField(
            model_name='timesheet',
            name='timesheet_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='timesheet',
            name='week_end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='timesheet',
            name='week_start_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='timesheet',
            name='company',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='connections.Company'),
        ),
        migrations.AlterField(
            model_name='timesheet',
            name='docket_shift',
            field=models.CharField(choices=[('Day', 'Day'), ('Night', 'Night')], max_length=20),
        ),
        migrations.AlterField(
            model_name='timesheet',
            name='equipment',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='equipment.Equipment'),
        ),
        migrations.AlterField(
            model_name='timesheet',
            name='equipment_hours',
            field=models.CharField(max_length=80),
        ),
        migrations.AlterField(
            model_name='timesheet',
            name='equipment_num',
            field=models.CharField(max_length=80),
        ),
        migrations.AlterField(
            model_name='timesheet',
            name='finish_time',
            field=models.TimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='timesheet',
            name='lunch',
            field=models.CharField(choices=[('0', '0 min'), ('5', '5 mins'), ('10', '10 mins'), ('15', '15 mins'), ('20', '20 mins'), ('25', '25 mins'), ('30', '30 mins'), ('35', '35 mins'), ('40', '40 mins'), ('45', '45 mins'), ('50', '50 mins'), ('55', '55 mins'), ('60', '60 mins')], default='30', max_length=20),
        ),
        migrations.AlterField(
            model_name='timesheet',
            name='project',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='projects.Project'),
        ),
        migrations.AlterField(
            model_name='timesheet',
            name='smoko',
            field=models.CharField(choices=[('0', '0 min'), ('5', '5 mins'), ('10', '10 mins'), ('15', '15 mins'), ('20', '20 mins'), ('25', '25 mins'), ('30', '30 mins'), ('35', '35 mins'), ('40', '40 mins'), ('45', '45 mins'), ('50', '50 mins'), ('55', '55 mins'), ('60', '60 mins')], default='30', max_length=20),
        ),
        migrations.AlterField(
            model_name='timesheet',
            name='start_time',
            field=models.TimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
