# Generated by Django 2.0.6 on 2018-08-17 11:30

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('timesheet', '0017_auto_20180817_2114'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timesheet',
            name='company_name',
            field=models.CharField(max_length=80),
        ),
        migrations.AlterField(
            model_name='timesheet',
            name='equipment_name',
            field=models.CharField(max_length=80),
        ),
        migrations.AlterField(
            model_name='timesheet',
            name='finish_time',
            field=models.TimeField(null=True),
        ),
        migrations.AlterField(
            model_name='timesheet',
            name='project_name',
            field=models.CharField(max_length=80),
        ),
        migrations.AlterField(
            model_name='timesheet',
            name='start_time',
            field=models.TimeField(null=True),
        ),
        migrations.AlterField(
            model_name='timesheet',
            name='timesheet_date',
            field=models.DateField(default=django.utils.timezone.now, null=True),
        ),
        migrations.AlterField(
            model_name='timesheet',
            name='week_end_date',
            field=models.DateField(null=True),
        ),
    ]
