# Generated by Django 2.0.6 on 2018-08-17 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timesheet', '0018_auto_20180817_2130'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='timesheet',
            name='equipment_hours',
        ),
        migrations.AlterField(
            model_name='timesheet',
            name='docket_shift',
            field=models.CharField(choices=[('Day', 'Day'), ('Night', 'Night')], default='Day', max_length=20),
        ),
        migrations.AlterField(
            model_name='timesheet',
            name='week_end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='timesheet',
            name='week_start_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
