# Generated by Django 2.0.6 on 2018-09-02 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timesheet', '0019_auto_20180817_2219'),
    ]

    operations = [
        migrations.AddField(
            model_name='timesheet',
            name='attachment_1',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name='timesheet',
            name='attachment_2',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name='timesheet',
            name='attachment_3',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name='timesheet',
            name='attachment_hours_1',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name='timesheet',
            name='attachment_hours_2',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name='timesheet',
            name='attachment_hours_3',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name='timesheet',
            name='equipment_finish_hours',
            field=models.CharField(default='TEST', max_length=80),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='timesheet',
            name='equipment_start_hours',
            field=models.CharField(default='TEST', max_length=80),
            preserve_default=False,
        ),
    ]
