# Generated by Django 2.0.6 on 2018-09-02 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timesheet', '0020_auto_20180902_1955'),
    ]

    operations = [
        migrations.AddField(
            model_name='timesheet',
            name='docket_num',
            field=models.CharField(default='TEST', max_length=80),
            preserve_default=False,
        ),
    ]
