# Generated by Django 2.0.6 on 2018-09-02 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timesheet', '0021_timesheet_docket_num'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timesheet',
            name='attachment_1',
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
        migrations.AlterField(
            model_name='timesheet',
            name='attachment_2',
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
        migrations.AlterField(
            model_name='timesheet',
            name='attachment_3',
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
        migrations.AlterField(
            model_name='timesheet',
            name='attachment_hours_1',
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
        migrations.AlterField(
            model_name='timesheet',
            name='attachment_hours_2',
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
        migrations.AlterField(
            model_name='timesheet',
            name='attachment_hours_3',
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
    ]
