# Generated by Django 2.0.5 on 2018-06-07 01:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import shortuuidfield.fields


class Migration(migrations.Migration):

    replaces = [('daily_dockets', '0001_initial'), ('daily_dockets', '0002_auto_20180213_0811'), ('daily_dockets', '0003_auto_20180214_0959'), ('daily_dockets', '0004_auto_20180403_1847'), ('daily_dockets', '0005_auto_20180416_1142'), ('daily_dockets', '0006_auto_20180424_1356'), ('daily_dockets', '0007_auto_20180502_1231'), ('daily_dockets', '0008_auto_20180521_1135'), ('daily_dockets', '0009_auto_20180521_1621'), ('daily_dockets', '0010_auto_20180522_1426'), ('daily_dockets', '0011_auto_20180522_2223'), ('daily_dockets', '0012_auto_20180523_0955'), ('daily_dockets', '0013_auto_20180523_1006'), ('daily_dockets', '0014_auto_20180523_1043'), ('daily_dockets', '0015_remove_docket_uuid')]

    initial = True

    dependencies = [
        ('equipment', '0001_initial'),
        ('projects', '0001_initial'),
        ('timesheet', '0004_auto_20180416_1142'),
        ('connections', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Docket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', shortuuidfield.fields.ShortUUIDField(blank=True, editable=False, max_length=22)),
                ('docket_date', models.DateField(blank=True, default=django.utils.timezone.now, null=True)),
                ('docket_day', models.CharField(choices=[('Monday', 'Monday'), ('Tuesday', 'Tuesday'), ('Wednesday', 'Wednesday'), ('Thursday', 'Thursday'), ('Friday', 'Friday'), ('Saturday', 'Saturday'), ('Sunday', 'Sunday')], default='Wednesday', max_length=20)),
                ('docket_shift', models.CharField(choices=[('Day', 'Day'), ('Night', 'Night')], default='Day', max_length=20)),
                ('equipment_name', models.CharField(max_length=80)),
                ('equipment_num', models.CharField(max_length=80)),
                ('equipment_hours', models.CharField(max_length=80)),
                ('attachments', models.CharField(blank=True, max_length=80)),
                ('company_name', models.CharField(max_length=80)),
                ('project_name', models.CharField(max_length=80)),
                ('supervisor', models.CharField(max_length=80, null=True)),
                ('start_time', models.TimeField(null=True)),
                ('finish_time', models.TimeField(null=True)),
                ('lunch', models.CharField(choices=[('0', '0 min'), ('5', '5 mins'), ('10', '10 mins'), ('15', '15 mins'), ('20', '20 mins'), ('25', '25 mins'), ('30', '30 mins'), ('35', '35 mins'), ('40', '40 mins'), ('45', '45 mins'), ('50', '50 mins'), ('55', '55 mins'), ('60', '60 mins')], default='30', max_length=20)),
                ('item1', models.BooleanField()),
                ('item2', models.BooleanField()),
                ('item3', models.BooleanField()),
                ('item4', models.BooleanField()),
                ('item5', models.BooleanField()),
                ('item6', models.BooleanField()),
                ('item7', models.BooleanField()),
                ('item8', models.BooleanField()),
                ('item9', models.BooleanField()),
                ('item10', models.BooleanField()),
                ('item11', models.BooleanField()),
                ('item12', models.BooleanField()),
                ('fault', models.TextField(blank=True)),
                ('reported_to', models.TextField(blank=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='connections.Company')),
                ('equipment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='equipment.Equipment')),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='projects.Project')),
                ('operator_sign', models.TextField(blank=True, null=True)),
                ('supervisor_sign', models.TextField(blank=True, null=True)),
                ('timesheets', models.ManyToManyField(to='timesheet.Timesheet')),
                ('created_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('docket_num', models.PositiveSmallIntegerField(blank=True, default=1000, null=True)),
                ('slug', models.SlugField(blank=True, null=True)),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='docket',
            unique_together={('created_user', 'docket_num')},
        ),
        migrations.AlterModelOptions(
            name='docket',
            options={'ordering': ('created_user__id', '-docket_num')},
        ),
        migrations.RemoveField(
            model_name='docket',
            name='timesheets',
        ),
        migrations.RemoveField(
            model_name='docket',
            name='uuid',
        ),
    ]
