# Generated by Django 2.0.6 on 2018-08-12 09:38

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('daily_dockets', '0015_auto_20180811_0850'),
    ]

    operations = [
        migrations.AlterField(
            model_name='docket',
            name='attachments',
            field=models.CharField(max_length=80),
        ),
        migrations.AlterField(
            model_name='docket',
            name='company',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='connections.Company'),
        ),
        migrations.AlterField(
            model_name='docket',
            name='docket_date',
            field=models.DateField(default=django.utils.timezone.now, null=True),
        ),
        migrations.AlterField(
            model_name='docket',
            name='docket_day',
            field=models.CharField(choices=[('Monday', 'Monday'), ('Tuesday', 'Tuesday'), ('Wednesday', 'Wednesday'), ('Thursday', 'Thursday'), ('Friday', 'Friday'), ('Saturday', 'Saturday'), ('Sunday', 'Sunday')], default='Sunday', max_length=20),
        ),
        migrations.AlterField(
            model_name='docket',
            name='equipment',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='equipment.Equipment'),
        ),
        migrations.AlterField(
            model_name='docket',
            name='operator_sign',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='docket',
            name='project',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='projects.Project'),
        ),
        migrations.AlterField(
            model_name='docket',
            name='supervisor_sign',
            field=models.TextField(null=True),
        ),
    ]
