# Generated by Django 2.0.6 on 2018-08-12 13:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0009_attachment'),
        ('daily_dockets', '0016_auto_20180812_1938'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='docket',
            name='attachments',
        ),
        migrations.AddField(
            model_name='docket',
            name='attachment',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='equipment.Attachment'),
        ),
        migrations.AddField(
            model_name='docket',
            name='attachment_hours',
            field=models.CharField(default='TEST', max_length=80),
            preserve_default=False,
        ),
    ]
