# Generated by Django 2.0.6 on 2018-08-27 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('daily_dockets', '0019_auto_20180817_2022'),
    ]

    operations = [
        migrations.AlterField(
            model_name='docket',
            name='docket_day',
            field=models.CharField(choices=[('Monday', 'Monday'), ('Tuesday', 'Tuesday'), ('Wednesday', 'Wednesday'), ('Thursday', 'Thursday'), ('Friday', 'Friday'), ('Saturday', 'Saturday'), ('Sunday', 'Sunday')], default='Monday', max_length=20),
        ),
        migrations.AlterField(
            model_name='docket',
            name='supervisor',
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
    ]
