# Generated by Django 2.0.6 on 2018-09-02 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('daily_dockets', '0021_auto_20180902_1530'),
    ]

    operations = [
        migrations.AddField(
            model_name='docket',
            name='fault_found',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
    ]
