# Generated by Django 2.0.6 on 2018-09-02 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('daily_dockets', '0022_docket_fault_found'),
    ]

    operations = [
        migrations.AlterField(
            model_name='docket',
            name='fault_found',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=20),
        ),
    ]
