# Generated by Django 2.0.6 on 2018-06-18 11:23

from django.db import migrations, models
import shortuuidfield.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FileImport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('csv_import', models.FileField(blank=True, null=True, upload_to='csv_import/')),
                ('uuid', shortuuidfield.fields.ShortUUIDField(blank=True, editable=False, max_length=22)),
                ('slug', models.CharField(max_length=80, unique=True)),
            ],
        ),
    ]
