# Generated by Django 2.0.6 on 2018-11-05 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('create_forms', '0004_auto_20181026_1501'),
    ]

    operations = [
        migrations.AddField(
            model_name='formitem',
            name='removed',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='formitem',
            name='checkbox',
            field=models.BooleanField(),
        ),
    ]
