# Generated by Django 2.0.6 on 2018-11-07 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('create_forms', '0005_auto_20181105_1616'),
    ]

    operations = [
        migrations.AddField(
            model_name='formitem',
            name='order',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
