# Generated by Django 2.0.6 on 2018-11-08 00:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('create_forms', '0006_formitem_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='formitem',
            name='text',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='formitem',
            name='order',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
