# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-01-29 10:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import shortuuidfield.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', shortuuidfield.fields.ShortUUIDField(blank=True, editable=False, max_length=22)),
                ('slug', models.CharField(max_length=80, unique=True)),
                ('company_name', models.CharField(blank=True, max_length=80)),
                ('webaddress_company', models.CharField(blank=True, max_length=120)),
                ('company_email', models.EmailField(blank=True, max_length=80)),
                ('company_phone', models.CharField(blank=True, max_length=20)),
                ('company_status', models.CharField(choices=[('Working With', 'Working With'), ('Have Worked', 'Have Worked'), ('Yet To Work', 'Yet To Work')], default='Working With Them', max_length=20)),
                ('linkedin', models.CharField(blank=True, max_length=120)),
                ('facebook', models.CharField(blank=True, max_length=120)),
                ('twitter', models.CharField(blank=True, max_length=120)),
                ('additional_info', models.TextField(blank=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', shortuuidfield.fields.ShortUUIDField(blank=True, editable=False, max_length=22)),
                ('slug', models.CharField(max_length=80, unique=True)),
                ('company_name', models.CharField(blank=True, max_length=80)),
                ('first_name', models.CharField(max_length=80)),
                ('last_name', models.CharField(max_length=80)),
                ('job_title', models.CharField(blank=True, max_length=80)),
                ('email_work', models.EmailField(blank=True, max_length=80)),
                ('phone_mobile', models.CharField(blank=True, max_length=20)),
                ('phone_work', models.CharField(blank=True, max_length=20)),
                ('contact_status', models.CharField(choices=[('Working With', 'Working With'), ('Have Worked', 'Have Worked'), ('Yet To Work', 'Yet To Work')], default='Working With Them', max_length=20)),
                ('linkedin', models.CharField(blank=True, max_length=120)),
                ('facebook', models.CharField(blank=True, max_length=120)),
                ('twitter', models.CharField(blank=True, max_length=120)),
                ('location', models.CharField(blank=True, max_length=80)),
                ('additional_info', models.TextField(blank=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('order', models.IntegerField(default=0)),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='connections.Company')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
