# Generated by Django 2.0.6 on 2018-06-25 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('connections', '0002_auto_20180618_2121'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='company_status',
            field=models.CharField(choices=[('Working With', 'Working With'), ('Have Worked', 'Have Worked'), ('Yet To Work', 'Yet To Work')], default='Working With', max_length=20),
        ),
    ]
