# Generated by Django 2.0.6 on 2018-07-07 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('connections', '0004_auto_20180705_1952'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='company_status',
            field=models.CharField(choices=[('Warm', 'Warm'), ('Hot', 'Hot'), ('Cold', 'Cold')], default='Warm', max_length=20),
        ),
        migrations.AlterField(
            model_name='contact',
            name='contact_status',
            field=models.CharField(choices=[('Warm', 'Warm'), ('Hot', 'Hot'), ('Cold', 'Cold')], default='Warm', max_length=20),
        ),
    ]
