# Generated by Django 2.0.6 on 2018-08-27 07:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('connections', '0005_auto_20180707_1718'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='company_status',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='contact_status',
        ),
    ]
