# Generated by Django 2.0.6 on 2018-08-27 07:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_auto_20180705_1952'),
        ('connections', '0006_auto_20180827_1704'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='project',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='projects.Project'),
        ),
    ]
