# Generated by Django 2.0.6 on 2018-08-27 07:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('connections', '0007_contact_project'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='location',
        ),
    ]
